// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SW42xf-CisV5f1mpjy0-6XvxOlhzMKA',
    appId: '1:669932001566:web:84eae1380b09526a65910f',
    messagingSenderId: '669932001566',
    projectId: 'nomor-2-b9c18',
    authDomain: 'nomor-2-b9c18.firebaseapp.com',
    databaseURL: 'https://nomor-2-b9c18-default-rtdb.firebaseio.com',
    storageBucket: 'nomor-2-b9c18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SW42xf-CisV5f1mpjy0-6XvxOlhzMKA',
    appId: '1:669932001566:web:84eae1380b09526a65910f',
    messagingSenderId: '669932001566',
    projectId: 'nomor-2-b9c18',
    databaseURL: 'https://nomor-2-b9c18-default-rtdb.firebaseio.com',
    storageBucket: 'nomor-2-b9c18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5SW42xf-CisV5f1mpjy0-6XvxOlhzMKA',
    appId: '1:669932001566:web:84eae1380b09526a65910f',
    messagingSenderId: '669932001566',
    projectId: 'nomor-2-b9c18',
    databaseURL: 'https://nomor-2-b9c18-default-rtdb.firebaseio.com',
    storageBucket: 'nomor-2-b9c18.appspot.com',
    iosClientId: '20069081129-kpk3ptgbjshorq8ohp2fd1kr2edepgj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomor2uasmade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5SW42xf-CisV5f1mpjy0-6XvxOlhzMKA',
    appId: '1:669932001566:web:84eae1380b09526a65910f',
    messagingSenderId: '669932001566',
    projectId: 'nomor-2-b9c18',
    databaseURL: 'https://nomor-2-b9c18-default-rtdb.firebaseio.com',
    storageBucket: 'nomor-2-b9c18.appspot.com',
    iosClientId: '20069081129-3muog0qp24jurp1gfi89sm45rk5unk72.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomor2uasmade.RunnerTests',
  );
}
